# Project Euler Problem 2: "Even Fibonacci numbers"
# 
#E ach new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import sys
sys.path.insert(0, './Utils')
import benchmark

sumOfEvens = 0
fibonacci = 1
fibonacciPrevious = 1
while 1:
	temp = fibonacci
	fibonacci = fibonacci + fibonacciPrevious
	fibonacciPrevious = temp

	if fibonacci > 4000000:
		break
	
	if fibonacci % 2 == 0:
		sumOfEvens += fibonacci

print ("The sum of evens is " + str(sumOfEvens))